spring:
  profiles:
    default: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect

jwt:
  secret: ENC(NMHO5QOhkLEeeSWD5CV+c4LuMCCP0L4rvnWw5/WjguZtEqPPSY5LKl0PXVfoIFOdobzZQojUHM0zWKlHDyoRaiM5KvYfjsqUFxRv7nc5fXFkOMdaoAESOd6CzLhcjEfm5l6BrS8/1qk=)
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/art-run?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate.hbm2ddl.auto: update
    show-sql: true
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: map-matching-group
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://10.50.224.3:3306/art-run  # Private IP
    username: root
    password: ENC(jMriZ0Fdkcyq6wVQj5Zn4f9SHmpAwyNcb3gDCOWSaN4=)
  jpa:
    properties:
      hibernate.hbm2ddl.auto: update
  redis:
    host: 10.76.2.16
    port: 6379
  kafka:
    bootstrap-servers: 10.80.10.5:9092
    consumer:
      group-id: map-matching-group